const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~KSRDRRTB#jLLzHkybR08znl66UXaDX31ebTupzKW_oLj-Cm-ZVgM"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
